### ISSUE TITLE
Json minify error

### ISSUE THREAD

**Issue by Daijinryuu** [deluvsushi/AminoSpamKilla#1]
Please help Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 1, in <module>
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/amino/__init__.py", line 9, in <module>
    from .sub_client import SubClient
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/amino/sub_client.py", line 13, in <module>
    from json_minify import json_minify
ModuleNotFoundError: No module named 'json_minify'

**Comment by deluvsushi** [comment]
pip install json_minify
