### ISSUE TITLE
strange error 

### ISSUE THREAD

**Issue by juscelinoxvr** [deluvsushi/AminoSpamKilla#2]
Script by deluvsushi
Github : https://github.com/deluvsushi
            _                              _   _ _ _   
 __ _ _ __ (_)_ _  ___ ____ __  __ _ _ __ | |_(_) | |__ _
/ _` | '  \| | ' \/ _ (_-< '_ \/ _` | '  \| / / | | / _` |
\__,_|_|_|_|_|_||_\___/__/ .__/\__,_|_|_|_|_\_\_|_|_\__,_|
                         |_|                           

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 8, in <module>
AttributeError: module 'amino' has no attribute 'Client'

[Program finished]

**Comment by deluvsushi** [comment]
pip uninstall amino.py && pip install amino.py
